### ISSUE TITLE
Use upstream images for manifests

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#10]
Replace any mention of images from `quay.io/modh/odh-ml-pipelines/*` with upstream images coming from `quay.io/operatorhub/`. This includes test case manifests and the sample cr.

**Comment by anishasthana** [comment]
cc @rimolive @gmfrasca

**Comment by HumairAK** [comment]
we now have ci pushing to upstream quay org for all component images: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env
