### ISSUE TITLE
When using a custom artifactscript, apiserver pod needs to be restarted

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-operator#131]
When using a [custom artifact script](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/samples/custom-configs/dspa.yaml#L21-L23) _after a dspa was already deployed_ (using default artifact script), the apiserver pod needs to be restarted so the custom artifact script configmap is used. The DSPO should do this automatically so that only the dspa field needs to be updated and apiserver is re-deployed to consume the new custom artifact script.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1633
