### ISSUE TITLE
Set up dev env for Tekton driver for v2

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#138]
As we continue to learn more about V2 and the tekton driver implementation, it would be beneficial for the team to create a doc in setting up a dev env for dsp with v2 integration.

Acceptance Criteria:

* A doc for anyone in the community to reproduce a setup, shouldn't be dependent on IDE

* Demo + video is a plus

**Comment by gregsheremeta** [comment]
pasting comments from Ricardo here:

DSP repo is up to date. https://github.com/opendatahub-io/data-science-pipelines

the v2 branch is kfpv2

fork dsp repo, git clone, and import in your favorite IDE.

The code is spread in multiple locations, but I believe this is the right starting point: https://github.com/opendatahub-io/data-science-pipelines/tree/kfpv2/backend/src/v2/driver

Also, it is good understand v2 architecture. So this doc will help you: https://docs.google.com/document/d/1fHU29oScMEKPttDA1Th1ibImAKsFVVt2Ynr4ZME05i0/edit
