### ISSUE TITLE
Investigate why DSPv2 manifests require additional SCCs to execute pipelines successfully.

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#141]
The kfp-tekton team added SCCs for using Kfp v2 with tekton driver in OpenShift. We need to understand the reasons for this and whether we can either workaround this, or propose/implement a fix.

Acceptance criteria: 

* Investigate why custom SCCs are required to run kfp v2 with tekton driver on OpenShift, more specifically why are these scc's required for pipeline runs. 
* Propose workarounds or fixes (the scope of this issue is not to implement these fixes, until we can confirm the solution).

**Comment by HumairAK** [comment]
SCC is added [here](https://github.com/kubeflow/kfp-tekton/blob/v2-integration/manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml). The portion of the SCC required to make V2 work on OCP is the following:  



```
runAsUser:
 type: RunAsAny
users:
- system:serviceaccount:kubeflow:pipeline-runner
```

This allows the pods created for each Pipeline within openshift to be able to run as the user specified in the image being used for the pipeline. 

> _runAsUser: …Defaults to user specified in image metadata if unspecified…_[[1]](https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_security_context.md)

**Why is this a problem?**

> By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node [[1]](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi6s6Lps_3_AhW-k4kEHcpLDBsQFnoECAgQAw&url=https%3A%2F%2Fdocs.openshift.com%2Fcontainer-platform%2F4.8%2Fopenshift_images%2Fcreate-images.html&usg=AOvVaw1QDpAcES0VrCMlspR9EGi3&opi=89978449)

**Why is this needed?**

Couple of reasons: 


1. When Pip installs packages, it utilizes a default cache folder 
    *  In the official `docker.io/python:3.9.x`
        It seems to be located in /.cache
    * seems non-root user does not have access to this in the official image
    * non-root user _does_ have access to this for python images from [red-hat registry](https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?container-tabs=gti)

2. When Pip installs packages it moves the bin to [the local folder](https://stackoverflow.com/questions/30274743/what-is-the-purpose-of-home-local) on the file system
    * In the official `docker.io/python:3.9.x`
        It seems to be located in /.local
    * The context here is identical to the .cache folder in (1). Docker python images prevent non-root users from accessing this path, while in the python images from red-hat registry, this is not an issue. 
    * Errors encountered (also note warning for 1), taken from pipeline taskrun pod:
      * `WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.`
      * `ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'`
3. `/tmp/kfp` is another directory that’s created for which the non-root user cannot access
4. Upstream KFP [will create folders](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/launcher_v2.go#L701-L739) `/minio, /gs, /s3 `for artifact output, depending on the protocol used (example if using Minio storage, it will attempt to create & and store artifacts within /minio)
    * non-root user does not have access to these folders mounted at root `/`

As a result of 1/2/3/4, the provided SCC uses the UID set by the Pipeline Image, which allowed the non root (arbitrary) user (as enforced by default in OCP) to bypass these restrictions

**Workarounds**:

Use a base image for your pipeline that adds all these paths to allow arbitrary uids to access by adding them to Group 0, for example: 


```Dockerfile
FROM docker.io/python:3.9.17

WORKDIR /
RUN mkdir .cache .local minio /tmp/kfp
RUN chgrp -R 0 /.cache && \
  chmod -R g=u /.cache && \
  chgrp -R 0 /tmp/kfp && \
    chmod -R g=u /tmp/kfp && \
  chgrp -R 0 /.local && \
    chmod -R g=u /.local && \
  chgrp -R 0 /minio && \
    chmod -R g=u /minio
```


This solution seems like it would be _very_ restrictive, you basically have to have the _right_ image that grants such permissions. 

**What fix is required to not restrict images?**

In my testing I was able to update the Tekton Launcher code that creates the TaskRun (i.e. Pipeline job Pod) and mount the folders:` /.cache, ./local, /tmp/kfp, /minio` as `emptydir`. This only partially worked. Because KFP creates these folders with a umask of 0644, non-root users cannot create directories within this path. There is an [upstream PR](https://github.com/kubeflow/pipelines/pull/7916/files) to fix this but it may have been forgotten.

I tested with the mask in the PR (0755) and it worked for the [data-passing](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components/Data%20passing%20in%20python%20components%20-%20Files.py) example in kfp , (it would work with 0744 as well). 

Concerns with this solution is every Taskrun would mount an empty dir for 4 different directories (that I know of). I’m not sure if this is that big of a deal though.

**Resources**:  

* PR to fix file perms: https://github.com/kubeflow/pipelines/pull/7916/files
    * Was fixed earlier for v1 as well https://github.com/kubeflow/pipelines/issues/7213
    * Possible regression in v2
* Explaining contract for /gcs
    * https://github.com/kubeflow/pipelines/issues/5673

**Comment by robpblake** [comment]
@HumairAK One observation as a newb to the project at this point: It _might_ make life easier if we could introduce the concept of a workspace where everything is written to. For example if the parent directory `/tmp/kfp` exists as the "workspace" and then everything else exists relative to this e.g `/tmp/kfp/minio`, `/tmp/kfp/.cache` then it should reduce the amount of permission wrangling and also reduces the cognitive load on users as to "where stuff is".

**Comment by HumairAK** [comment]
@robpblake I agree with you, and I think upstream considered this but decided against this due to: https://github.com/kubeflow/pipelines/issues/5673
