### ISSUE TITLE
Identify list of features available in V2 kfp that are not in V1 kfp

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#145]
We currently don't have a good grasp of what features are available in Kfp v1 that are not available in KFP v2, ibm kfp-tekton team may be a good source of this on how to go about figuring this out. Outcome should be a best effort document that outlines the differences

**Comment by rimolive** [comment]
This [link](https://www.kubeflow.org/docs/components/pipelines/v2/version-compatibility/) is the reference for v1 <-> v2 feature parity we need.
