### ISSUE TITLE
Implement odh-to-rhods branch/promotion strategy

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#146]
Study the ODH to Rhods auto merging doc to get an understanding of odh -> rhods promotion strategy and how we should handle incubation, outline the process for DSP, set up the odh -stable branch and ensure that the automated merges to rhods are happening via this branch.

Figure out how we will promote features for incubation, set up a call, and drive the discussion.

 

Acceptance criteria:

* automatic merges from odh-stable to rhods via dev ops merge tooling 
* a doc presenting how to promote incubation/features in odh to rhods for dsp
* doc should outline how to resolve hot fixes to rhods (how do we keep downstream behind upstream if an critical fix needs to go in to rhods?).

**Comment by gregsheremeta** [comment]
(internal) doc: https://docs.google.com/document/d/16JvVzp-cPDg5jPZpAPDZ2D6-ZCj_5gUbzcICwHsUBEA/edit

**Comment by gregsheremeta** [comment]
spawned #273 #274 #275
