### ISSUE TITLE
Document a “user story” for data science pipelines “provenance” capabilities

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#148]
We know that users want to be able to “track things” in/about their experiments/pipelines, but we don't have a good feel for what those things are.  The goal of this task would be to clearly document a user scenario around this that we can then start to build towards.

It may be something like “I want to register metadata about the data souce that I used to train the model in this experiment. I want to register key performance/accuracy metrics about the model that was trained in this eperiment.”

We should get feedback from downstream IBM, RHODS field, BU teams on what we come up with for this.

**Comment by rimolive** [comment]
Chris Chase agreed with all MLMD v2 capabilities and potentially we can collect more requirements when we have a beta version of our own UI w/ provenance capabilities

**Comment by accorvin** [comment]
_Red Hat Internal:_ We have a (deprecated) internal tracker for this [here](https://issues.redhat.com/browse/RHODS-8318) for additional context.

**Comment by rimolive** [comment]
@accorvin We collected enough information about this issue, and I feel from the community also agrees that MLMD v2 has everything we need to cover that story. If you are fine with it, I'll mark this issue done.

**Comment by accorvin** [comment]
@rimolive is there a doc or anything like that that was produced for this that I can review?

**Comment by rimolive** [comment]
@accorvin This is the first version of the document: https://docs.google.com/document/d/16qBI5U2uwAAwqCBh6f_ClZ0yJEiDzCtiV0Y1JQmk7Is/edit?usp=sharing

Any feedback is very welcome.

**Comment by accorvin** [comment]
@rimolive can you give me comment access on that document?

**Comment by rimolive** [comment]
@accorvin  Done, you can now make comments.

**Comment by accorvin** [comment]
@rimolive @gregsheremeta I really like this updated version of the doc. 🚢 from me

**Comment by rimolive** [comment]
Good to hear! I'm closing this task then.
