### ISSUE TITLE
Infer "secure" field in a dspa if it is not provided.

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#157]
Currently odh-dashboard offers no option to use "secure: false" connection for object storage connection, so the only way to use an insecure "http" connection for your object storage is to go in the backend and update the dspa manually. We should infer this scheme if it's not provided, this way dashboard does not need to provide a field for this.

Acceptance criteria:
Infer "secure" field in dspa if it is not provided (consider removing it entirely but if this api change results in a lot of overhead go with former option).

**Comment by jedemo** [comment]
I would like to prioritize this issue based on feedback

**Comment by jedemo** [comment]
@jkoehler-redhat - this is a field priority. I don't think it's being tracked in Jira

**Comment by andrewballantyne** [comment]
> @jkoehler-redhat - this is a field priority. I don't think it's being tracked in Jira

FWIW, this is a backend thing, and thus we would need to tag @accorvin

**Comment by shalberd** [comment]
yeah, default of CRD [datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml#L459) is secure: true and probably never given a chance to be overridden in an instance / CR?

**Comment by amadhusu** [comment]
PR Raised to remove the "secure" field after testing that it doesn't hinder any normal operation.

**Comment by shalberd** [comment]
Ok, so the secure field is removed from odh pipelines operator ... will you ensure insecure is only done for internal cluster service addresses e.g. http://myminio.myproject.svc:whateverport?
