### ISSUE TITLE
Rename Declarative Tests to include purpose

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#163]
The Declarative blackbox tests (found in `./controllers/tesdata/declarative`) are generically named `case_0`, `case_1`, etc.  I found the framework supports naming them more purposefully so let's add concise but descriptive names such that we know what each of these tests are actually doing

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1634
