### ISSUE TITLE
Update Oauth Proxy to 4.10

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#166]
For both apiserver and mlpipeline ui

Coordinate this update with dashboard: https://github.com/opendatahub-io/odh-dashboard/issues/1400

**Comment by amadhusu** [comment]
Verified we aren't using <4.10 oauth proxy anywhere in our code base in dsp.

**Comment by HumairAK** [comment]
thanks @amadhusu !
