### ISSUE TITLE
[Spike] Evaluate kube-linter features and check which ones can be important to implement

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-operator#168]
kube-linter can be a useful tool to check for any rules we should follow for ODH core, like add liveness/readiness probes, set resources/limits, etc.

We need to check which checks kube-linter might be important to use, and implement a GitHub action for that.

Acceptance criteria: 
Suggest a list of checks what we should employ in dspo/dsp, follow up task will be to implement

**Comment by rimolive** [comment]
kube-linter documentation with all possible checks: https://docs.kubelinter.io/#/generated/checks

**Comment by rimolive** [comment]
Suggested checks to use from kube-linter: access-to-create-pods, access-to-secrets, dangling-networkpolicy, dangling-service, default-service-account, duplicate-env-var, env-var-secret, exposed-services, invalid-target-ports, latest-tag, mismatching-selector, no-liveness-probe, no-readiness-probe, non-existent-service-account, unset-cpu-requirements, unset-memory-requirements

**Comment by HumairAK** [comment]
> access-to-create-pods
> access-to-secrets

can we remove these, the DSPO needs to create secrets/deployments, and the linter will fail on these: 


```
<standard input>: (object: <no namespace>/data-science-pipelines-operator-manager-rolebinding rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) binding to "data-science-pipelines-operator-manager-role" clusterrole that has [create] access to [deployments], [create] access to [deployments], [*] access to [deployments replicasets], [*] access to [jobs], [*] access to [pods], [*] access to [*], [*] access to [*] (check: access-to-create-pods, remediation: Where possible, remove create access to pod objects in the cluster.)

<standard input>: (object: <no namespace>/data-science-pipelines-operator-manager-rolebinding rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) binding to "data-science-pipelines-operator-manager-role" clusterrole that has [create delete get list patch update watch] access to [secrets], [*] access to [*], [*] access to [*] (check: access-to-secrets, remediation: Where possible, remove get, list and watch access to secret objects in the cluster.)


```

**Comment by rimolive** [comment]
Accepted kube-linter checks:
- dangling-networkpolicy
- dangling-service
- default-service-account
- duplicate-env-var
- env-var-secret
- exposed-services
- invalid-target-ports
- latest-tag
- mismatching-selector
- no-liveness-probe
- no-readiness-probe
- non-existent-service-account
- unset-cpu-requirements
- unset-memory-requirements

**Comment by rimolive** [comment]
Created a follow-up issue to implement the kube-linter checks: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/193 and close this issue as Done
