### ISSUE TITLE
DSPO will not create/reconcile DSPA if DB Secret is missing

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#172]
If the Secret that a DSPA.database.ExternalDB references does not exist, the DSPO will log an error and not attempt to create/apply the DSPA.  This is likely fine, but now the DSPA appears to the DSPO as in-sync and will not Reconcile indefinitely, even if the missing secret/key is created.  This means the DSPA will always be stuck as undeployed until the DSPA CR is edited.

**Comment by HumairAK** [comment]
This will be resolved along with: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/173 
Please refer to that issue for keeping track of this.
