### ISSUE TITLE
E2E Pipeline sample for v1

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#174]
Write an e2e pipeline sample that illustrates the full user experience workflow of training, validating, deploying a model in ODH leveraging DSP. The pipeline should utilize a reasonable set of features that we expect majority of the use cases to cover and should be able to be used as an exhaustive example to show case DSP and it's capabilities. 

Part of this task is to investigate what feature set to demo in this pipeline, the above is a suggestion.

Acceptance criteria: 

Upload both the .py and compiled formats of the pipeline.
Instructions on how to run this, with a brief explanation about the pipeline.

**Comment by gregsheremeta** [comment]
This is mostly implemented by Trevor here: https://github.com/rh-datascience-and-edge-practice/kubeflow-pipelines-examples

There is some value in adding to what Trevor has built, but we want to concentrate on building examples and tutorials for v2. There is some value in doing so for v1, though, but I'm not sure we'll have time to get to it.
