### ISSUE TITLE
Automated PRs to odh-manifest

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#178]
A github action that, when provided a tag version input will open a pr in odh-manifest that will sync the data-science-pipelines-operator manifests that reside here: 

https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main/config

with target dest here: 
https://github.com/opendatahub-io/odh-manifests/tree/master/data-science-pipelines-operator 

Make the automation as generic as possible. Allow filtering of paths/files (e.g. like a .gitignore), as other odh components may want to re-use this work.

Related #177  (ideally this workflow would trigger right after automated releases complete, can be part of same workflow as well)

NOTE: There may be already some effort in ODH proper to automate this, sync up with odh community on this.

**Comment by DharmitD** [comment]
Reopening this issue because the workflow failed when we tried creating a tag for v1.2.x release.
