### ISSUE TITLE
[Spike] Investigate persistent log archiving in dsp

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#180]
This is a feature that is available kfp upstream, we currently do not have this enabled in DSP, because it requires mounting of hostpath volumes. A more robust solution will likely be needed (e.g. openshift logging),

Acceptance criteria: 

* Propose logging solution, ADR.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1635
