### ISSUE TITLE
Start an ADR on Upstream DSPO/DSP testing

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#181]
Formulate a Doc with QE, that identifies a robust/thorough process on what tests need to be included in DSPO and DSP, come to a conclusion on how / where/ when it should run. 

ADR should identify: 

What kind of tests (unit/e2e/integration), and where they should run (pr/nightly/etc.)

Acceptance criteria: 
Start the adr pr, a follow up issue will handle ongoing managing of this pr via correspondence, fixes, etc.

**Comment by gmfrasca** [comment]
ADR PR opened: https://github.com/opendatahub-io/architecture-decision-records/pull/15
