### ISSUE TITLE
Declarative Tests do not clean up after themselves

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#182]
The Declarative tests leave behind artifacts and use a shared test bed, which can affect test results.  This was verified by updating the `case_3` test which should have verified a resource wouldn't be created when ExternalDB/Storage was specified, but the secret still existed.  renaming the test `case_0` would make the test pass, suggesting the resource was left over from a previous case.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1636
