### ISSUE TITLE
The ability to operate pipelines programmatically

### ISSUE THREAD

**Issue by blublinsky** [opendatahub-io/data-science-pipelines-operator#189]
KFP client support the execution of many pipeline operations that are very useful for programmatic KFP usage.
It requires a token for accessing pipeline URL
````
kfp_tekton.TektonClient(host=host, existing_token=token)
````
A common way for obtaining such token is:
````
cert = "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
client = kfp_tekton.TektonClient(host=route, existing_token=token, ssl_ca_cert=cert)
client.create_run_from_pipeline_func(pipeline_func=flipcoin_pipeline, arguments={})
`````
Unfortunately, no service account currently provides a token that can be used for client creation.
Can we please, create and advertize one for this purpose?

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1638
