### ISSUE TITLE
Need reference to Dockerfile for building this image: 'quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui'

### ISSUE THREAD

**Issue by VaishnaviPatil35036** [opendatahub-io/data-science-pipelines-operator#194]
To Deploy DSP instance need to build image 'quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui' on Power

Not able to find repository building image 'quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui'

On quay https://quay.io/repository/opendatahub/odh-ml-pipelines-frontend-container, in description we see-
Description
No repository description has been set

dspa_simple.yaml- https://github.com/opendatahub-io/data-science-pipelines-operator/blob/70eab9e27a75be23cf89c54df48db3bcbf81fde8/config/samples/dspa_simple.yaml#L17C45-L17C45

**Comment by HumairAK** [comment]
Thanks, added: https://quay.io/repository/opendatahub/odh-ml-pipelines-frontend-container?tab=info
