### ISSUE TITLE
Feature request - KFP python SDK with ODH pipelines

### ISSUE THREAD

**Issue by vishnudev-k** [opendatahub-io/data-science-pipelines-operator#197]
Our team wants to use KFP python SDK to trigger pipeline runs from Python code. As I came to know the feature is not yet available or won't work without manual intervention of injecting browser cookies into the code.

**Comment by shalberd** [comment]
@HumairAK @rimolive this ticket raises a valid point, how to trigger pipeline runs without ODh dashboard GUI

**Comment by HumairAK** [comment]
@vishnudev-k you should be able to trigger pipelines via the sdk in code, some instructions here: https://github.com/opendatahub-io/data-science-pipelines-operator#using-the-api -- does this work for you?

**Comment by HumairAK** [comment]
@vishnudev-k closing this issue out, if the above does not work, please feel free to re-open with further clarification!

**Comment by vvarala1** [comment]
I would like to trigger a pipeline run programmatically from my local environment. I am interested to use KFP package with Argo workflow as backend to connect to dspa instance (Pipelines API server) in a namespace. Could you @HumairAK update the instructions accordingly? I would highly appreciate if you show me how to get `_oauth_proxy` cookie to authenticate programmatically in Python code and submit a pipeline run. I deployed Openshift AI operator 2.13 version on the cluster.
