### ISSUE TITLE
Implement a solution for how to proceed with file permission handling in v2.

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#198]
As a follow up to https://github.com/opendatahub-io/data-science-pipelines-operator/issues/141, we want to coordinate with upstream to make the necessary changes to lift the requirements for `RunAsAny` SCC requirement for  `pipeline-runner` SA

**Comment by HumairAK** [comment]
Another possibility is to confirm whether the workaround proposed in #141 is sufficient (i.e. just require images to have proper arbitrary uid support), but this will still require changes to umask as mentioned in #141

**Comment by shalberd** [comment]
having current images in my view would be the cleaner approach, it just needs to be documented. Nice work, @HumairAK and @guimou. It is a challenge using upstream Kubeflow sometimes, but I guess you might have better access to upstream kubeflow as well.

**Comment by guimou** [comment]
In #141, @HumairAK said "This solution (having specific images) seems like it would be very restrictive, you basically have to have the right image that grants such permissions."
This is exactly what we did for the notebook images anyway. The ones from upstream Kubeflow are simply unusable on OpenShift (unless you allow anyone running as root of course...). So I don't see this solution of having base compatible runtime images really restrictive. Just as for notebooks we need specific images for OpenShift/Enterprise grade environments.

**Comment by guimou** [comment]
If/when needed, it would be pretty easy to implement the workaround described in #141 and have the folders with suitable permissions created directly in the base runtime image (and then propagated to the whole chain).
@atheo89 @harshad16 for awareness.

**Comment by harshad16** [comment]
Thanks for sharing the info @guimou

**Comment by rimolive** [comment]
There is a PR to rebase Data Science Pipelines v2 from latest v2-integration branch in kfp-tekton repo. I also added the fix for the file permissions.

https://github.com/opendatahub-io/data-science-pipelines/pull/126

**Comment by HumairAK** [comment]
We updated the umask being used for the artifact directories that are created. So as long as users use an image that allocates the appropriate permissions within the image, they should be able to run their pipelines without issues. We will follow up with a specification for images, and look into whether we should provide such images (and if so, work towards that effort in follow up tasks).
