### ISSUE TITLE
DSPA Hard Codes external storage credentials

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/data-science-pipelines-operator#199]
When creating a DSPA application, the Dashboard requires you to configure a data connection containing, credentials, bucket, and host details.

When the dashboard creates the DSPA application the bucket, host, port, and scheme are all hard coded into the object instead of pulling from the secret object that the dashboard has forced us to create.  If any of those details need to be updated they are updated the user would update the secret and restart the pod, expecting those to be pulled directly from the secret, and not copied/hard coded into the DSPA object.

**Comment by HumairAK** [comment]
This sounds like a feature request to allow to update credentials via dashboard, no?  

I'm not sure we want users directly managing their secrets via ocp console and restarting pods, if they are using odh-dashboard. 

If they are not using odh-dashboard, and just using standalone dsp, then I don't see a problem with interfacing directly with the DSAP CR to update the non-secret values of their s3 storage connection.

**Comment by strangiato** [comment]
> This sounds like a feature request to allow to update credentials via dashboard, no?

There is absolutely a part of this request that should be managed on the UI side.  I'm happy to open up addition issues there as well.

> I'm not sure we want users directly managing their secrets via ocp console and restarting pods, if they are using odh-dashboard.

Why is it that you expect people to use only one or the other?  I would expect that a normal path would be to use the dashboard for basic capabilities, and when they need more advanced capabilities to work directly with the YAML.  

If I am editing the secret keys, there is no other way than to manually restart the pods to get them loaded into the container, so why would you not expect users to do that?

> If they are not using odh-dashboard, and just using standalone dsp, then I don't see a problem with interfacing directly with the DSAP CR to update the non-secret values of their s3 storage connection.

In this case, it seems like the Dashboard team has a pretty good idea of using a secret (or possibly a configmap) for users to manage connection details, and they wanted to us that to load the host details.  It would be great if the operator supported this option since this is a great way to manage these details.

I am honestly surprised the dashboard team didn't ask for this themselves considering that the workflow that they created certainly implies that this is how it should work under the hood.

**Comment by HumairAK** [comment]
>Why is it that you expect people to use only one or the other? 

Sorry I should have been more clear, in this case I was referring for users using the dashboard. Dashboard creates the DSPA based on the connection details provided via dashboard, so if you're changing the secret created by dashboard (or you provided), and expecting the dashboard to update the DSPA with this info accordingly, this change needs to be reflected by dashboard, not the dsp operator. This looks like it will be [addressed here](https://github.com/opendatahub-io/odh-dashboard/issues/1214). If you want to bypass the dashboard, you can try updating the secret referenced within the DSPA, and the connection details within the DSPA itself, I'm not sure if that would be over-written by dashboard though. 

If you are deploying DSP standalone, the DSPA and external connection secrets are being managed manually, and in this case the user should be able to update these resources directly, in the case of non-secret values like host/port, you can update the DSPA directly and pods should auto re-create, for credentials like the secret access-key you will need to update the secret you provided within the dspa and restart the api server pod.

**Comment by HumairAK** [comment]
Closing as it is stale (and lack of capacity), if you/anyone feels this issue is still relevant, or ought to be addressed, please re-open or create a new issue.
