### ISSUE TITLE
CRD Spec should have more informed descriptions and list possible values

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#200]
As per title. We want more detailed descriptions on the fields of the CRD, in cases where there are limited selection of values, the description should state what those values are. For example "scheme" can be "http" or "https". We should inform the user via CRD description as such. 

Example of how to add a description: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/api/v1alpha1/dspipeline_types.go#L25

Acceptance criteria: 
Each .spec field should have a description for the end-user, listing out possible values, types, defaults, wherever applicable.

**Comment by jgarciao** [comment]
I've verified that the changes are included in RHOAI 2.6 
![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/66894/be5a0d88-12c5-4354-a6db-0891f56eba9f)
