### ISSUE TITLE
Subcomponent Reconcilers should fetch manifests from 'internal' template dir dynamically

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#201]
The various subcomponent reconcilers (apiserver.go, database.go, etc) each reference a list of static, hard-coded filenames which makes adding additional files/manifests tedious (need to update code whenever new file is added/renamed/removed).

Implement a code pattern change such that each of these reconciliation functions dynamically fetch the list of files to template and deploy instead, thereby removing hardcoded/magic filepaths.

**Comment by gmfrasca** [comment]
There may be instances of when conditional logic is required.  Therefore, it may be an idea to seperate the 'always-deployed' and 'conditional' manifests into folders as well, such as `all` and `conditional`, respectively.  (There likely is a better naming convention to follow than this, for what it's worth)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1640
