### ISSUE TITLE
Add Regex to prevent invalid database dbname and username metadata 

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#207]
MariaDB will fail to deploy if a DSPA provides non-compliant values for the dbname, username, and/or password.  Since the Regular Expressions are already defined, let's reuse/implement them in the DSPA CRD to block invalid metadata for the dbname and username.  

Since the password is contained in a Secret and therefore not controlled by the DSPO directly, it would be a bit trickier or not possible from the controller's standpoint to block invalid inputs.  For now let's just handle dbname and username.

Regexs, as expected by MariaDB:
```
  MYSQL_USER (regex: '^[a-zA-Z0-9_]+$')
  MYSQL_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
  MYSQL_DATABASE (regex: '^[a-zA-Z0-9_]+$')
```

**Comment by jgarciao** [comment]
@gmfrasca I believe these regexp will be valid for Unquoted identifiers, but MariaDb allows using almost all ascii characters when using backquotes  (e.g. `table-db`). There is more info in [the docs](https://mariadb.com/kb/en/identifier-names/) and some examples [here](https://stackoverflow.com/questions/35592034/how-do-i-add-database-name-with-hyphen-character-using-script-in-ubuntu)

**Comment by HumairAK** [comment]
> @gmfrasca I believe these regexp will be valid for Unquoted identifiers, but MariaDb allows using almost all ascii characters when using Quoted Identifiers (e.g. table-db). There is more info in [the docs](https://mariadb.com/kb/en/identifier-names/) and some examples [here](https://stackoverflow.com/questions/35592034/how-do-i-add-database-name-with-hyphen-character-using-script-in-ubuntu)

@jgarciao it seems that the mariadb container is more stricter than it should be, they don't seem to make exceptions for quoters identifiers. Seems to me we have to go with the stricter restrictions placed upon us by the image implementation: 


For instance, when trying to use back tics: 
![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/10904967/85bbcab0-45f9-494b-aaf1-3de9e981f77e)

![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/10904967/5973fd4c-4d35-44cf-8272-fe3cceed21c6)

This check seems like it's sourced from: [1](https://github.com/sclorg/mariadb-container/blob/771e9947261d9f6f851e25741b086a0771006619/root-common/usr/share/container-scripts/mysql/pre-init/20-validate-variables.sh#L6) [2](
https://github.com/sclorg/mariadb-container/blob/771e9947261d9f6f851e25741b086a0771006619/root-common/usr/share/container-scripts/mysql/common.sh#L50C25-L50C40)
