### ISSUE TITLE
[Spike] Using cli tools to push objects to storage may result in performance issues

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#209]
Currently we consume the upstream solution to pushing output artifacts to s3 via s3 cli tools, in our case `aws s3`, this may not scale, or result in performance dregadations, such as time outs, bottlenecks, etc. 

The purpose of this task is to investigate the current solution, identify these performance issues, and suggest solutions.

**Comment by HumairAK** [comment]
We should confirm the behavior of s3 artifact passing in v2 as well, and if it differs with v1.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1642
