### ISSUE TITLE
[SPIKE] Investigate ways in which odh/dsp upgrades can impact running pipelines.

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-operator#217]
Investigate on handling running pipelines during the ODH/DSP upgrade.

Refer to the DSP Upgrade testing ADR for further details [1].

[1] https://github.com/opendatahub-io/architecture-decision-records/pull/14

**Comment by amadhusu** [comment]
I will link a doc with the impacts on Running Pipelines during ODH/DSP upgrade to this issue.

**Comment by amadhusu** [comment]
The draft document for this is complete, making minor adjustments and will be updating this issue with the doc on 6th October.

**Comment by gregsheremeta** [comment]
what's the status of this? can you link to the doc here?

**Comment by amadhusu** [comment]
Linking the Doc here as I finished most of it today.

**Comment by amadhusu** [comment]
Draft linked [here](https://docs.google.com/document/d/1GPKNS3m_fnGT6OgaKjqjODot43M9jWaxCbq-2BA2ZBo/edit#heading=h.5rk41wmisp1o)

**Comment by HumairAK** [comment]
lgtm
moved the doc [here](https://drive.google.com/drive/folders/1sB5RZXvRvCQX4I-yAhtqSXJL0ECFv1hQ)
