### ISSUE TITLE
Leverage ObjStore Routes for Prereq Health Checks

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#221]
Follow-up for #149, depends on #220

Implement a way for the <strike>Database and</strike> Object Store Pre-deploy Health Check to leverage a managed route if the option is enabled.  

Essentially, in the current state, an external DSPO (running either locally or on an external cluster) will never pass the prerequisite DB/Storage health checks because the urls provided in DSPAParams will reference local services, which are inaccessible locally.  Right now the only way around this is to disable the health checks, but this leaves gaps in stability and testing/debugging coverage.  If an external Route *is* created though, we would be able to leverage this to enable the health checks, so implement a way to enable this behavior and override url/host values the DSPAParams.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1643
