### ISSUE TITLE
SPIKE: Investigate building images genericly using RHTAP

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#226]
OpenShift CI will be replaced by Red Hat Trusted Application Pipelines (RHTAP) to build images. We need to familiarize ourselves with that new build system to collect some ideas on how to effectively build Data Science Pipelines images, as well as handle exceptions like https://github.com/opendatahub-io/data-science-pipelines-operator/issues/142.

**Comment by rimolive** [comment]
Document with some findings about RHTAP: https://docs.google.com/document/d/1b6aoP_rWkt8UuZgBDVwYR8bd9m_EzqQWNRjQafEF04Y/edit?usp=sharing

**Comment by HumairAK** [comment]
lgtm
