### ISSUE TITLE
Use openshift-goimports to sort go importants

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#239]
### Feature description

We should follow openshift best practices when organizing our go imports, we should utilize [openshift go imports for this](https://github.com/openshift-eng/openshift-goimports).

Acceptance criteria: 
* Figure out how best to include this as part of development workflow, (can this be part of pre-commit?)
* add a gh action to verify that PRs adhere to the imports via openshift go imports. 
* Also add a documentation  to dspo readme on how to develop/run go imports when developing.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1644
