### ISSUE TITLE
[Feature Request]: Mount config directory and use in Persistence Agent Deployment

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#241]
### Feature description

In upstream KFP v1.7.1, there was a change made to the Persistence Agent code that now expects and requires the config.json configuration file (the same one currently used by the API Server Deployment) to also be passed in as a parameter to the agent executable.

In practice, this means copying the `volume` and `volumeMount` sections from API Server into the appropriate places on the PersistenceAgent manifests, and adding the item `- '--config=/config'` to the list of args passed to the container.  Note that this should be done *only* once Data Science Pipelines pulls down the v1.7.1 changes from upstream

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1646
