### ISSUE TITLE
[Feature Request]: Add DB and ObjStore Connection metadata env vars to Persistence Agent

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#242]
### Feature description

Somewhat Related to https://github.com/opendatahub-io/data-science-pipelines-operator/issues/241

Once the PersistenceAgent is upgraded to v1.7.1+, it will now take in a configuration as it now connects to the db and objstore.  This means we need to propogate the connection metadata env vars from the API server to the PersistenceAgent as well.  In particular, we need to provide these envvars: 

- `DBCONFIG_USER`
- `DBCONFIG_PASSWORD`
- `DBCONFIG_DBNAME`
- `DBCONFIG_HOST`
- `DBCONFIG_PORT`
- `DBCONFIG_CONMAXLIFETIMESEC`
- `OBJECTSTORECONFIG_BUCKETNAME`
- `OBJECTSTORECONFIG_ACCESSKEY`
- `OBJECTSTORECONFIG_SECRETACCESSKEY`
- `OBJECTSTORECONFIG_SECURE`
- `MINIO_SERVICE_SERVICE_HOST`*
- `MINIO_SERVICE_SERVICE_PORT`*
*these could just be provided by openshift via env vars provided when a Service `minio-service` exists.

In practice, this just means copying these envvars and their values/templates/sourcerefs from the APIServer manifest.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1647
