### ISSUE TITLE
How to use http protocol with juypter notebook

### ISSUE THREAD

**Issue by orangeji11** [opendatahub-io/data-science-pipelines-operator#263]
I am a beginner, the questions I ask may be relatively basic :)
I can see the [network policy](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/5d453f6fa2770082c068f51d887d56edf24ad101/config/internal/common/policy.yaml.tmpl#L15C1-L15C1) in DSPO has any peer with port 8443(https protocol),that means that https services can be accessed from anywhere in the cluster, but the same http protocol in the [network policy](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/5d453f6fa2770082c068f51d887d56edf24ad101/config/internal/common/policy.yaml.tmpl#L21) is only for some DSPO services, but how to use http protocol in private cloud scenarios?

**Comment by HumairAK** [comment]
@orangeji11 current implementation does not allow for direct connections to the DSP api-server. 

The upstream kfp implementation has the server accept insecure connections so we put an oauth proxy infront of it to secure traffic going into the server. I guess the current work around would be to manually append the networkpolicy, the operator won't overwrite additions. But you would be opening up your dsp server to be accessible by any pod in any namespace (unless you have additional networking infra to prevent this like istio/service mesh). 

We can look into whether we can allow insecure connections via oauth proxy and make that an optional feature you can enable via DSP if it's possible. 

You can also create a redirect ocp route.

**Comment by HumairAK** [comment]
@orangeji11 closing this issue out as I believe it was answered. If you continue to face issues around this please feel free to re-open, or create any follow up issues!

If you'd like to make a specific request on making insecure connections, I would make a follow up issue with the usecase described.
