### ISSUE TITLE
Provide UX with long running KFP v2 environments

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#268]
Deploy long running KFP v2 environments and provide ODH Dashboard team with access to them, so that this may serve as a reference. One kfp-tekton v2, one kfp-argo based (vanilla kubeflow)

**Comment by gregsheremeta** [comment]
@gregsheremeta has done this and has scripts, so if someone else takes this, ping me

**Comment by rimolive** [comment]
Closing this issue as we agreed that we already have it deployed
