### ISSUE TITLE
Provide UX with exhaustive list of what artifact displays (v1) UI will need to account for

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#269]
In a call with UX, there was confusion on how to Dispaly certain outputs, and/or what the exhaustive list of outputs and visualizations exist in kfp v1 that dashboard team needs to account for in ODH Dashboard.

We should provide them with docs/examples/pipelines with an exhaustive list of what visualizations exist in v1 (e.g. confusion matrix).

**Comment by HumairAK** [comment]
Available viewer types in v1: https://www.kubeflow.org/docs/components/pipelines/v1/sdk/output-viewer/#available-output-viewers

**Comment by gregsheremeta** [comment]
wrote this up in a google doc: 
[internal] https://docs.google.com/document/d/1NL3A5pbpaEF27olR5V6IJxrL_amb8TWmoDT9v4nO8zE/edit
