### ISSUE TITLE
figure out if we want to use a "release stream" branch to feed downstream nightlies

### ISSUE THREAD

**Issue by gregsheremeta** [opendatahub-io/data-science-pipelines-operator#274]
figure out if we want to use a "release stream" branch to feed downstream nightlies

(internal) doc that describes the nightlies: https://docs.google.com/document/d/16JvVzp-cPDg5jPZpAPDZ2D6-ZCj_5gUbzcICwHsUBEA/edit

**Comment by HumairAK** [comment]
related: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/143
