### ISSUE TITLE
document hotfix flow

### ISSUE THREAD

**Issue by gregsheremeta** [opendatahub-io/data-science-pipelines-operator#275]
document hotfix flow. For example, say there's a CVE or hotfix that needs to be applied to all supported releases immediately. Document the flow for that.

(internal) doc where this came up: https://docs.google.com/document/d/16JvVzp-cPDg5jPZpAPDZ2D6-ZCj_5gUbzcICwHsUBEA/edit

**Comment by HumairAK** [comment]
I added some docs on the steps to follow for patch release here: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/docs/release/release_workflow.md#patch-releases

**Comment by gregsheremeta** [comment]
perfect, think we can close this then
