### ISSUE TITLE
Write a simple test, defined in the Upstream Testing ADR, that leverages upstream testing infrastructure

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#285]
Tests should be platform agnostic. Infra should utilize tests but the tests should be able to be executed in any infra (openshift-ci, jenkins, travis etc)

Also consult with QE on this ( @diegolovison )

**Comment by HumairAK** [comment]
We spoke to @jgarciao and @diegolovison, and we agree this needs to be a collaboration between dsp dev/qe. Currently qe is backlogged with other work. So this issue should be picked up when @jgarciao or @diegolovison have the bandwidth for it, in collaboration with dev.

**Comment by HumairAK** [comment]
More action items to include as part of this ticket: 
1. Create mechanism to run nightly integration suite
4. Run tests on dsp release

**Comment by jgarciao** [comment]
I just learnt about the existing integration tests for opendatahub-operator, that could be an example we could use (in code and also execution process). I'm getting more info from @LaVLaS and @VaishnaviHire 
https://github.com/opendatahub-io/opendatahub-operator/issues/563
