### ISSUE TITLE
[SPIKE] Investigate/Define Nightly Build Strategy

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#286]
We need an opinion prepared on how we handle ODH nightly builds with DSPO/DSP.  Note that this should not be all-encompassing, but just a simple strategy documented (perhaps a few sentences maximum)

ACC/Questions to answer as a comment on this TASK:
- What branch to build on
- Where manifests come from
- Will the current trajectory of nightlies being handled conflict with the DSP release strategy and cadence

**Comment by HumairAK** [comment]
The nightlies are now fully referencing upstream ODH manifests. 

* The sources file can be found [here](https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/blob/rhods-1.18-rhel-8/upstream_sources.yml). 

* Builds are from the default branches (master/main)
* Manifests are all pulled from opendatahub-io GH org
* This should not affect release strategy, we should always make sure our manifests work with other components in their most latest ODH iteration (i.e. default branches). The only way it may conflict is if a dsp dependent ODH component (like odh dashboard, or elyra), does not put latest ODH content (i.e. changes expected to go in next odh upcoming release) in main/master of their respective branches
* There is a cluster where nightlies are built and deployed to daily. Currently this cluster can be found [here](https://console-openshift-console.apps.explor-rhoai.npvm.s1.devshift.org). Whether this will remain to be the case is unclear. If this link goes down, reach out to QE for the latest cluster. 


### Can these nightlies be deployed in other clusters? 
Maybe. I tried but got blocked on requiring access to http://registry.stage.redhat.io, I think if we had an sa/token for this registry then it should work. Steps that got me this far: 

1. Get images from jenkins builds [here](https://jenkins-cvp-617017858ebd9a62aec7c3b8.apps.ocp-c1.prod.psi.redhat.com/view/all/job/cvp-redhat-operator-bundle-image-validation-test/)
  * Search for jobs prefixed with `cvp-redhatopenshiftdatascience - odh-operator-bundle-container-v1.18.0` these are the nightly builds, the "1.18" is arbitrary/non-meaningful.
3. Allow insecure registry [registry-proxy.engineering.redhat.com](http://registry-proxy.engineering.redhat.com/) in your ocp cluster: 

```
oc patch image.config.openshift.io/cluster --type merge --patch '{"spec":{"registrySources":{"insecureRegistries":["registry-proxy.engineering.redhat.com","registry.stage.redhat.io"]}}}' image
```

4. Add pull secret for http://registry.stage.redhat.io 
5. ??
