### ISSUE TITLE
[Feature Request]: Deprecate host/scheme for external obj store, and introduce a full host value

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#288]
### Feature description

Currently when adding an external object storage, scheme/host are entered separately. This continues to pose difficulties for odh-dashboard when parsing these separately, as users are likely to enter these as one endpoint, then DSPO will rejoin them after the fact, and the whole thing becomes a pointless endeavor. 

We should instead look into just providing the option to enter scheme+host as one field value that the dashboard team can fill out.

Deprecate the old fields by adding field descriptors identifying as such, with log warnings, to allow for backwards api compatibility, and smooth transition for dashboard.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1652
