### ISSUE TITLE
[Feature Request]: Move Functional Tests to it's own directory

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#289]
### Feature description

The Functional test suite (suite_test.go + dspipeline_controller_func_test.go) are *not* unit tests in the traitional sense and it is somewhat confusing to include them with the rest of the white-box unit tests that exist in the `controllers` package (which are all also suffixed `_test.go`).

For organization reasons let's move them to their own directory to keep the pattern consistent throughout the repository, with `_tests.go` within the `controllers` package existing next to their files-under-test and the Ginkgo/Functional tests in their own `functional_tests` directory

**Comment by gmfrasca** [comment]
Note - this will require some updates to some relative filepaths.  @HumairAK found at least these three instances, althought there may be more: [[1]](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/498a0f9832c071e6d5b3c58130db175dcdd9f5a1/controllers/suite_test.go#L105), [[2]](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/498a0f9832c071e6d5b3c58130db175dcdd9f5a1/controllers/suite_test.go#L132), [[3]](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/498a0f9832c071e6d5b3c58130db175dcdd9f5a1/controllers/testutil/util.go#L37)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1653
