### ISSUE TITLE
Use specialized builds for pre-commit images 

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#3]
We are [using a generic ubi](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/.github/build/Dockerfile) and installing python/golang within them, we can instead use multi stage builds to add more security, and reduce the size of the image.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1631
