### ISSUE TITLE
[Feature Request]: Remove hardcoded artifact destination in artifact_script

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#301]
### Feature description

The artifact script always publishes all artifacts to a `/artifacts` prefix which is not very scalable.  Implement a way to remove the hardcoded prefix

Instances
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/internal/apiserver/artifact_script.yaml.tmpl#L12
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/internal/apiserver/artifact_script.yaml.tmpl#L15

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1654
