### ISSUE TITLE
[Bug]: Pipeline steps pods report "permission denied" errors to "/.docker"

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Standalone DSPO (without ODH)

### Version

v1.31

### Environment

* OCP Pipelines Version: 1.11 
* OCP Version: 4.13

### Current Behavior

Pipelines step pods show warning messages: 

```txt
2023/09/05 14:51:24 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.docker: permission denied
```

This is likely an openshift gotcha due to images being run with arbitrary ids. It doesn't seem to affect the workflow behavior/logic, but it is not the great seeing this in every log messages. We also should understand the full implications of this warning and if it's something we need to be concerned about.

This is kind of related to: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/198 
Where the question of should we support "any images may be relevant.

### Expected Behavior

We expect these warning messages to not show.

### Steps To Reproduce

1. Deploy DSPO/DSPA
2. Deploy flip coin
3. Inspect pipeline pod logs, they all should have this message

### Workaround (if any)

Use pipeline images that give arbitrary ids permission to .docker (by addhing this directory to grp 0)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1655
