### ISSUE TITLE
[Feature Request]: Use openly available MariaDB image

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#321]
### Feature description

In relation to: https://github.com/opendatahub-io/opendatahub-community/issues/100 

[MariaDB image](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L11) uses the image from `registry.redhat.io`, which requires authentication, and is thus not freely accessible anonymously. We should look for open alternatives to this image and update it accordingly. 

Note also that when the image is switched, we will need to update our release tooling to reflect the changes: 
* [params.py](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/scripts/release/params.py)
* [compatibility doc ](https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main/docs/release)
  * this one might be more trickier to handle since we have been storing it as mariadb-103, if the new image doesn't follow this naming convention, we will need to reformat the table

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1658
