### ISSUE TITLE
 [Feature Request]: Use openly available Oauth Proxy image

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#322]
### Feature description

Related: 
* https://github.com/opendatahub-io/opendatahub-community/issues/100
* https://github.com/opendatahub-io/data-science-pipelines-operator/issues/321

[Oauth Proxy](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L12) image uses the image from registry.redhat.io, which requires authentication, and is thus not freely accessible anonymously. We should look for open alternatives to this image and update it accordingly.

This is a bit different from issue 321, in that Oauth Proxy is something used across ODH and we will need to stay aligned with the rest of ODH in this. As such we should seek broader input on this. 

Note that just like 321, we may need to update the following depending on the images used: 
* [params.py](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/scripts/release/params.py)
* [compatibility doc ](https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main/docs/release)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1659
