### ISSUE TITLE
[Feature Request]: DSPO upgrade testing advanced checks

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-operator#323]
### Feature description

DSP upgrade testing workflow and some basic checks would be covered in https://github.com/opendatahub-io/data-science-pipelines-operator/issues/216

Next set of tests could be:

- Spinning up a pipeline amidst the upgrade testing and ensuring that DSPA resources stay intact even post upgrade. Make sure that the operator isn't restarting the DSPA pods, because that might lead to pipeline failure.
- Checking operator pod logs to catch any errors. For example, the immutable fields error that comes up when upgrading operator labels.
- Check CR status conditions to make sure that the DB, APIServer, etc are still working.

**Comment by DharmitD** [comment]
FYI @jgarciao @diegolevison could you please elaborate on these points if required, or add any more checks that would need to be covered?

**Comment by diegolovison** [comment]
It appears to be a promising starting point, and we can progress from there.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1660
