### ISSUE TITLE
[Spike] Investigate contribution tasks for the model registry team for their mlmd strategy

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#332]
Model registry team is looking into adding custom implementations on top of mlmd (replacing the server with a possible superset of features), we should understand what impacts this may have from DSP side, and whether this is something DSP should also look to utilize or benefit from.

**Comment by rimolive** [comment]
Proposed contribution topics:

[Create a DB Dump from MLMD tables and share with the Model Registry team](https://github.com/opendatahub-io/data-science-pipelines/issues/133 )
[Work with Model Registry to ensure MLMD feature parity in their API](about:blank)
[[Spike] Work on a proposal for a kfp SDK extension to support Model Registry new artifact types](about:blank)
