### ISSUE TITLE
[Spike] Figure out strategy around backwards compatibility and support for older OCP versions

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#333]
We seem to be hitting walls regarding when we can upgrade to catch up to upstream, example from v[1.7 upgrade thread](https://github.com/opendatahub-io/data-science-pipelines/issues/118): 

> 1.7 Requires Tekton 0.47. This is introduced in OCP Pipeline 1.11. The earliest OCP adoption for this is 4.12. Which means We have to wait until OCP EOL's 4.11 before proceeding with this change.

We constantly face obstacles around having to support older OCP due older OCP Pipelines versions when looking to upgrade dsp (kfp). We should formalize what the process/policy ought to be here, and push for a practical solution whereby we are not constantly blocked on releases due to EOL support dates for OCP.

Some questions to answer: 
1. Is it a hard requirement we wait until an OCP version reaches EOL before upgrading to a specific OCP Pipelines version? 
2. Can we support older/newer versions in a given release? (olm / dspa / odh-dashboard feature enablement options)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1664
