### ISSUE TITLE
[Bug]: Import Pipeline button is ready before pipeline server is ready to serve

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/data-science-pipelines-operator#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

RHODS Operator 1.33.0

### Environment

Any

### Current Behavior

Error during the import.

![selenium-screenshot-7](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/687311/fb06d975-bb1e-4b91-99c6-52cefcbc600d)

### Expected Behavior

Import pipeline button must be enabled once the pods are readyThe import

### Steps To Reproduce

Create a workbench
Create a data connection
Create pipeline server
Once the Import pipeline button is ready, try to import the pipeline ( be fast )

### Workaround (if any)

Refresh the page and import the pipeline again

**Comment by diegolovison** [comment]
We also have the following Error Message before the Pipeline Server becomes ready
![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/687311/908175fa-d2cf-4f84-83d5-033a0b37b929)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1666
