### ISSUE TITLE
[Feature Request]: Slim Down v2 ClusterRoles

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#354]
### Feature description

The ClusterRoles used in v2 manifests are very generous and can probably be pared down to a stricter spec, to help minimize our security footprint

**Comment by DharmitD** [comment]
PR to Slim down v2 ClusterRoles: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/442
PF details on the updates made as part of this PR, in this [doc.](https://docs.google.com/document/d/1PdtePscGG1P6KBNgUY0r0l5LvVKyI8zojoAmn9c06pw/edit?usp=sharing)

**Comment by DharmitD** [comment]
PR to add certain resources back to v2 ClusterRoles: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/458

**Comment by DharmitD** [comment]
Closing as related PRs are merged.
