### ISSUE TITLE
Set up Snyk scans for dsp/dspo repo

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#356]
As a follow up to: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/279 

Set up a dsp-developers snyk org account, import dsp/dspo repos, and disable automated prs.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1668
