### ISSUE TITLE
[Feature Request]: Set a reasonable request size for Manager

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/data-science-pipelines-operator#359]
### Feature description

Currently the manager sets the request sizes to the following:

```
requests:
  cpu: 10m
  memory: 64Mi
```

In the following location:

https://github.com/opendatahub-io/data-science-pipelines-operator/blob/1a8be8374f2c64168aa3a5013c93994c270c5f1e/config/manager/manager.yaml#L81

This request size is unreasonable and should be adjusted to reflect a more reasonable amount needed to start the application.

Based on a quick observation in a brand new install the manager uses at minimum 350Mi and 60m at idle with no DSPA objects deployed on the cluster.

Requests should be the minimum amount of cpu/memory the application requires to run.  It is assumed that a pod will be able to use up to the limits but if the pod is deployed on an over committed node it may not ever have access to more cpu/memory than the request.

If you set the request as the limit the pod will not be able to start and will continuously be killed and throttled.

### Describe alternatives you've considered

I would highly recommend taking a look at Vertical Pod Autoscaling recommender mode if you are not familiar with pod sizing.  It is normally recommended to have about 7 days of metrics for the recommender to create a suggestion but it is generally a great tool for this exercise.  Goldilocks is also a nice addition to VPA to create a nice UI with the reccommendations.

### Anything else?

If you want to update it without testing I would recommend at least the following:

```
requests:
  cpu: 200m
  memory: 400Mi
```

**Comment by HumairAK** [comment]
@strangiato absolutely agree, we will take a look at adjusting these values so they better reflect the resources required to run the controller.

**Comment by HumairAK** [comment]
For assignee: get confirmation from QE on the new requests that are suggested

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1669
