### ISSUE TITLE
[Feature Request]: Implement DSPA version switch in CRD

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#361]
### Feature description

Implement a mechanism in DSPO such that a single field in a  DSPA CR (such as `DSPVersion`) can be set, and all images deployed for that DSPA will use the correct pipeline infrastructure version (v1, v2, etc)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1670
