### ISSUE TITLE
Deploy KFP v2 with Argo backend in a dev environment

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#363]

**Comment by gregsheremeta** [comment]
tried to install on k3s on an ubuntu VM -- install didn't come up -- traefik pod stuck in Error. I suspect the kubernetes version was too recent -- I might retry with 1.22 or something

deployed on kind in an ubuntu VM -- install worked, but default included pipelines don't work. Opened https://github.com/kubeflow/pipelines/issues/10028   Not sure if I can work around this one myself 🤔

**Comment by gregsheremeta** [comment]
got it working, handed off to UXD

instructions [internal]: https://docs.google.com/document/d/1XoZ7OLx4u4ekSKkLLERfOfvQRIVq_z7u4eI7KAtLvC4/edit
