### ISSUE TITLE
[Bug]: Import pipeline is generating a different yaml with a busy box image

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/data-science-pipelines-operator#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

RHODS 1.33

### Environment

OpenShift 4.13 and RHODS 1.33

### Current Behavior

Import pipeline with no reference to busybox.
Double check the generated yaml. It will contains busybox image there

### Expected Behavior

The imported yaml should be the same

### Steps To Reproduce

Import [iris-pipeline-compiled.zip](https://github.com/opendatahub-io/data-science-pipelines-operator/files/12819296/iris-pipeline-compiled.zip) in the UI
Go to OpenShift -> Pipelines -> Pipelines -> PipelineRuns -> YAML

![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/687311/77b4ea0d-13db-4c07-bbb7-ebf64196ea26)

**Comment by jgarciao** [comment]
We have reproduced this error in our test automation when using [this pipeline](https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/tests/Resources/Files/pipeline-samples/iris-pipeline-compiled.yaml)

The problems of using busybox image are:
- Pipeline runs often fail because steps like "copy-results-artifacts" fail because docker.io pull rate limit reached (see screenshot)
- Pipelines cannot run on disconnected clusters unless the busybox image is cached in a private registry

![rhods-1 34-v1-pre-rc-iris-pipeline-error-busybox](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/66894/904f319a-1ab9-4a72-9d58-0320acf011d2)

**Comment by jgarciao** [comment]
Related to https://github.com/kubeflow/kfp-tekton/pull/1336

**Comment by gregsheremeta** [comment]
the compiled yaml definitely says to use ubi for that container - https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/tests/Resources/Files/pipeline-samples/iris-pipeline-compiled.yaml#L297

that's just not being respected - because https://github.com/kubeflow/kfp-tekton/pull/1336 ?

**Comment by diegolovison** [comment]
The relationship between https://github.com/kubeflow/kfp-tekton/pull/1336 and this issue should be investigated.

**Comment by gmfrasca** [comment]
I tried uploading the pipeline @jgarciao provided via both the kfp and odh (v1.10) UIs and was unable to reproduce the issue.  

Also, if the said pipeline was already compiled then [kubeflow/kfp-tekton#1336 ](https://github.com/kubeflow/kfp-tekton/pull/1336) would be unrelated to this bug, as the only files changed would be involved are in the sdk and therefore you would see the `busybox` references in the pipeline YAML itself.

**Comment by gmfrasca** [comment]
Also, I extracted the [Pipeline definition](https://github.com/opendatahub-io/data-science-pipelines-operator/files/12819296/iris-pipeline-compiled.zip) provided in the initial Issue description by @diegolovison, and noticed that it does have `busybox` references for the `output-taskrun-name` and `copy-results-artifacts` containers of the training step, and as such i would expect the uploaded pipeline to also have these.

As with above, these are set at compile-time (generating the .yaml from the .py file), and can be overridden via the env var introduced in the kfp-tekton issue (ie `export TEKTON_BASH_STEP_IMAGE="quay.io/opendatahub/ds-pipelines-artifact-manager:latest"`) before running `python some-pipeline-definition.py`

**Comment by diegolovison** [comment]
Tested with RHODS and it is working fine. Thanks
