### ISSUE TITLE
[DSPv2] Investigate/Update/Remove minio-service annotation (tekton.dev/artifact_endpoint)

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#375]
There are one or more seemingly benign but hardcoded references to `minio-service` in annotations of various Deployments such as the APIServer.  Investigate to make sure these aren't actually used and either remove or update them to reference the actual s3 endpoint

**Comment by DharmitD** [comment]
Moving this into backlog, since this isn't a priority currently.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1671
