### ISSUE TITLE
Add system testing (live cluster) tests DSP tests

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#381]
Create 2 tests using ginkgo/gomega that will run in a live kind/openshift-ci/jenkins like environment

Test 1: 
* Execute a Pipeline and assess successful/failed completions 

Test 2: 
* Confirm artifact in s3 storage when using data passing

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1672
