### ISSUE TITLE
Migrate RDS external testing instance to new cloud account

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#382]
due by end of October

**Comment by gmfrasca** [comment]
New instance created with same credentials, configuration, etc.  Also transfered old data over so this should look identical to old RDS instance with the exception of a slightly updated URL.

Verifying with stakeholders (namely, DSP QE) if this is sufficient.  Once URL references are updated we can delete the old instance and close out this task.

**Comment by HumairAK** [comment]
@Jooho / @diegolovison fyi ^

**Comment by gmfrasca** [comment]
I think @HumairAK meant to tag @jgarciao :)
