### ISSUE TITLE
[spike] Confirm infra for e2e tests in disconnected environment

### ISSUE THREAD

**Issue by gregsheremeta** [opendatahub-io/data-science-pipelines-operator#407]
Overall Goal: 
Regularly run e2e tests in a disconnected environment to ensure that DSP and DSPO work in disconnected environments.

Goal for this issue: 
* Confirm with QE on the best practices Devs can follow to run regular e2e testing on disconnected environments
* Create any follow up tasks to further overall goal once confirmed

**Comment by accorvin** [comment]
cc @aloganat for awareness on this

**Comment by accorvin** [comment]
Also cc @apodhrad for awareness

**Comment by DharmitD** [comment]
Some notes based on discussion with @apodhrad 

RHODS QE is coming up with a Jenkins pipeline that will automate the entire process of spinning up a disconnected cluster. They are working on setting up a disconnected environment on AWS using the `kraken` framework. Here's [a script](https://www.google.com/url?q=https://gitlab.cee.redhat.com/strimzi/strimzi-ci/-/merge_requests/978&sa=D&source=docs&ust=1702395126261151&usg=AOvVaw0BAwYvSli2X3Klr-jEA5jG) which they've recently. designed for the same.
The "final" Jenkins pipeline, however, will have a few more pieces such as image registry automation, provision to monitor, etc - complete automation of the disconnected cluster set up process.

Here's [some documentation](https://my-abhi-docs.notion.site/Test-disconnected-installation-of-stack-320-cdb404c5bbe34d30a9210d77dbf9d4d4) on how we could set up a disconnected cluster manually, for the time being.

As for the timeline, the exact release date for the end-to-end automated Jenkins pipeline is still to be determined. Therefore, our next action item will be to reach out to the QEs during the upcoming sprint to get an update on when the Jenkins pipeline will be ready. Once it's available, we can proceed with onboarding our e2e tests onto the pipeline.

**Comment by shalberd** [comment]
Hi all, nice to see disconnected with all its aspects in on the radar, very encouraging to see this for pipelines as well.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1675
