### ISSUE TITLE
Add integration tests for external storage/db behind self-signed certs

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#412]
Related to: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/362 

We want to have tests that will test connections from api server + pipelines (artifact passing) and leverage external mino/db connections with secured self-signed certs and confirm server is deployed without issues, and jobs run to completion with artifacts successfully stored to object store, and db.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1676
