### ISSUE TITLE
[Feature Request]: Add Notification mechanism for Nightly GH Action

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#416]
### Feature description

The Nightly GH action only notifies the workflow file's most recent updater upon failures, so the rest of the team needs to manually check the results or they will be unaware of sanity/status.  Implement some mechanism that alerts (via email, slack, etc) a list or group of users whenever the workflow fails.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1677
