### ISSUE TITLE
[Feature Request]: Update dspa_test.go to use table-driven testing

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#421]
### Feature description

the tests found in `tests/dspa_test.go` has a pattern of running a set of 2 common command serially which is messy and less maintainable.  Update the section here to instead call these commands in a loop that iterates over a table, with each iteration having a respective input and matching output/verification

**Comment by HumairAK** [comment]
Blocked on : https://github.com/opendatahub-io/data-science-pipelines-operator/issues/285

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1678
