### ISSUE TITLE
[DSPv2] Remove kind/resource type mentions from metadata.name in resources

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#426]
There are dspv2 rbac that have the `*-clusterrole` or `*-clusterrolebinding` suffixes in metadata.name, example: [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/dspv2/config/v2/exithandler/controller/clusterrole.clusteraccess.yaml#L8)

We should remove these, don't need to know it's a clusterrole, when we can already see that in its kind resource

Do the same for any other resource that is prefixing the kind resource in metadata.name

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1680
