### ISSUE TITLE
[Bug]: ObjectStorage Health Check not detecting incorrect bucket name or required S3 ListBucket Permission

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/data-science-pipelines-operator#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

RHODS 1.34 RC2

### Version

RHODS 1.34 RC2

### Environment

* RHODS 1.34 RC2
* OpenShift Pipelines 1.12.1

### Current Behavior

In https://github.com/opendatahub-io/data-science-pipelines-operator/pull/133 ObjectStorage Health Check was introduced.

If you configure a data connection using proper data for the fields Access Key, Secret key, Endpoint and Region but using a non existing bucket name, the ObjectStoreAvailable CR condition for that DataSciencePipelinesApplication doesn't detect the problem and shows Status: True and Message: _Object Store connectivity successfully verified_.  

Some other conditions fail in this case (see screenshot below)

![incorrect-bucket-name-dspa-conditions](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/66894/115666b7-6506-473e-95d4-f74124910e23)

In case you use an incorrect access key, the ObjectStoreAvailable CR condition properly informs about the problem, as seen in this screenshot

![incorrect-access-key-dspa-conditions](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/66894/97d9ec42-599a-4713-bb80-6910b6725892)

### Expected Behavior

ObjectStoreAvailable CR condition should detect when the bucket doesn't exist

### Workaround (if any)

- Log in into RHODS Dashboard
- Create Data Science Project
- Create a data connection with correct data except for bucket name,  using a bucket name that doesn't exist
- "Create Pipeline Server"
- In OpenShift Console, search the DataSciencePipelineApplication created in the previous step and check the CR Conditions
- Verify the status and message for the ObjectStoreAvailable CR Condition

### Anything else

When the failure provoked by wrong access key happens, even if the ObjectStoreAvailable properly detects there is something wrong connecting to the storage, RHODS Dashboard just shows that there was an error with the pipeline server. I think this will be improved here: https://github.com/opendatahub-io/odh-dashboard/issues/1224

![incorrect-bucket-name-dashboard-error](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/66894/0fa0f0ab-0094-498a-9c37-4e1b20ae2b80)

**Comment by gmfrasca** [comment]
IIRC the reason this is an issue is because we'd need to expand minimum expected permissions for a standard user, since at present they potentially would not have ListBucket, and I believe that is  required to do this check.  @HumairAK helped in this investigation when we implemented #133, so thoughts?

**Comment by HumairAK** [comment]
Yeah I don't know what the protocol here is for us to expand bucket permission requirements, because we didn't need it before, I worry it could break this for existing users if we expand the perms required to make these checks.

**Comment by jgarciao** [comment]
@gmfrasca I'm verifying #262 in RHODS 2.4.0 and I see that, in case you provide correct AWS credentials, endpoint, region but wrong bucket name, the ObjectStoreAvailable CR condition will still say  "Object Store connectivity successfully verified" and I believe this is because of [this if statement](https://github.com/gmfrasca/data-science-pipelines-operator/blob/da60c8aa60c1152d5d594977d514642a00e2e71c/controllers/storage.go#L91).

Shouldn't the condition return False if the bucket doesn't exist (NoSuchBucket)?

**Comment by jgarciao** [comment]
Something else I found today: if all settings are correct but the AWS credentials don't provide ListBucket permission, the CR condition will still say "Object Store connectivity successfully verified" but RHODS Dashboard will be unable to start the pipeline server because pod ds-pipeline-pipelines-definition-xxx will CrashLoopBackOff

This is the IAM policy that provokes the cash:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/*"
            ]
        }
    ]
}
```

**Comment by HumairAK** [comment]
@jedemo any updates on this?

**Comment by jedemo** [comment]
Can you help me understand what additional permissions would need to be granted to standard RHOAI users? Are these OpenShift permissions? I'm not sure I understand the 'ListBucket' reference.

**Comment by HumairAK** [comment]
Apologies @jedemo I intended to ping @jgarciao the issue author for further info on this. These are permission issues direcdtly pertaining to deploying data science pipelines and it's interaction with s3/

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1684
