### ISSUE TITLE
[DSPv2] Remove cache server resources

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-operator#445]
Cache Server is a v1 component, and should be removed. Caching in v2 is now bundled within API Server.

Acceptance criteria: 
* Figure out what cache serverdependencies/assets need to removed that are no longer utilized in v2
* Remove all such dependencies/assets

**Comment by HumairAK** [comment]
Related: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/488

**Comment by HumairAK** [comment]
> Caching in v2 is now bundled within API Server.

@rimolive can you link where this is bundled in the repo?

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1685
