### ISSUE TITLE
[Feature Request]: Create an example how to integrate Pipelines with Ray

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/data-science-pipelines-operator#446]
### Feature description

Create an example how to integrate Pipelines with Ray

### Acceptance criteria 

* Create an example pipeline how to integrate Pipelines with Ray that can be used by QE, first pass, maybe eventually converted to something we can present to customers
* Identify location where to store DSP specific pipelines examples (like this one), figure out if these ought to be proposed upstream (consult team)

**Comment by HumairAK** [comment]
@gmfrasca any updates?

**Comment by diegolovison** [comment]
I will create a simple one and IBM will provide a complex one.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1686
