### ISSUE TITLE
Create known DSP Disconnected test cases

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#447]
Test cases to cover: 

- [ ] Test python package installs in pipeline via a a custom pip repo (internal repo, e.g. users using solutions like [this](https://jfrog.com/artifactory/) ) 
- [ ] Test minio connection behind self signed certs case, test should ensure custom bundle mounts on dspa's work as intended

**Comment by HumairAK** [comment]
As per @jgarciao , we currently have the ability to spin up real disconnected clusters (ease of this process still unknown)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1687
