### ISSUE TITLE
Create a library of pipeline examples covering Data Science Pipelines features

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-operator#455]
We need more pipeline examples to cover most (if not all) Data Science Pipelines features, such as:

* Artifact tracking
* End-to-end training
* Codeflare/Ray integration
* ExitHandler
* Retry
* etc.

- [ ] [[Feature Request]: Create an example how to integrate Pipelines with Ray #446](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/446)
- [ ] [E2E Pipeline sample for V2 #175](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/175)

**Comment by HumairAK** [comment]
We need to split this up in multiple tasks

Do not repeat upstream examples, link to those instead
Any example we add should be specific to odh/rhods use case

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1688
