### ISSUE TITLE
Some tekton components webhook are failling with SSL issues

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-operator#457]
Some webhooks in `openshift-pipelines` namespace that belongs to DSPv2 installation is falling with the following error:
```
2023/11/13 17:01:48 http: TLS handshake error from 10.129.0.47:56630: remote error: tls: bad certificate
```
We need to find the root cause and fix.

**Comment by HumairAK** [comment]
this is for tekton implementation

**Comment by HumairAK** [comment]
De-prioritizing tentatively.
