### ISSUE TITLE
Ensure Kustomize v5 support for DSPO/DSP

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#459]
DSPO deployment needs to support Kustomize v5 manifests, see odh tracker [here](https://github.com/opendatahub-io/opendatahub-operator/issues/714).

Need to ensure there will be no issues when ODH operator switches to buildling DSPO manifests via Kustomize v5. 

Note that Kustomize v5 does not support param.env   (since kustomize 3.2.1 actually) 

We use it fairly heavily in our manifests to do var substitution, we'll need to move away from that.

**Comment by hbelmiro** [comment]
Closing as we already support Kustomize v5.
