### ISSUE TITLE
[Spike] Investigate if  resource_references[]  response api object field has pipeline parent references for runs triggered via jobs

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#467]
This is a spike to help resolve this task: https://github.com/opendatahub-io/data-science-pipelines/issues/113 

In v1 scheduled jobs do not mention owning pipeline within the resource_references[] api response object. This makes querying for pipelines very difficult for odh dashboard. 

Acceptance criteria: 
1. Confirm this behavior exists in v2
2. If it does,  follow up with ux that the issue is resolved
3. If it does not, discuss with team/ux if this is something we should try to push to upstream, if so make an issue upstream as a follow up task
4. If 2/3 above result in no-op, close out issue 113

Some questions worth asking for (3), why did upstream not have this? is it not needed for their UI? Why do we need it? should upstream have it?

**Comment by amadhusu** [comment]
Sample API Responses for 

1.  Experiment Triggered Run
2.  Manually Triggered Run

Documented [here](https://docs.google.com/document/d/13joLvzHSF7oPu9UHYIKymU4BcNH2eBxfwo_23DAVWKk/edit#heading=h.l6t44kxq1jjr)

**Comment by HumairAK** [comment]
lgtm, thanks @amadhusu 

fyi @andrewballantyne / @harshad16
