### ISSUE TITLE
Strategy for carrying patches / use OpenShift commit checker

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#474]
Use the openshift commit checker. It can be run as an openshift CI pre-submit job. It basically just enforces a commit naming convention for our carried patches against our upstream. This will make it easy to rebase and to know what our carries are.

https://github.com/openshift/build-machinery-go/tree/master/commitchecker

[internal thread] https://redhat-internal.slack.com/archives/C05KDB2HFQQ/p1692989204792129

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1695
