### ISSUE TITLE
Document v1 -> v2 migration

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#475]
The doc should be high level view and outline the following: 

1. Impacted components (e.g. ocp pipelines installs, api server, db, etc.??)
2. What should be the Deprecation policy (will require confirmation from PM, what to deprecate, etc.) 
3. What onus is on end user vs us for sdk migrations (e.g. do we need to provide docs? etc.)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1696
