### ISSUE TITLE
[Feature Request]: GHWorkflow(s) deprecating set-output, update to use Environment Files

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#480]
### Feature description

Update any GitHub workflows to use Environment Files rather than the set-output action (the PR trigger Workflow at a minimum uses this), as that action is pending deprecation and will soon or eventually be fully disabled, breaking the workflow entirely.

More information: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1699
