### ISSUE TITLE
[Feature Request]: GHActions - Update any workflows that use github-script@v3.1.0 action

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#481]
### Feature description

Locate and update any workflows that use a common action "github-script" to something more recent, as this version is built on Node 12 which has reached End-of-life and therefore produces an override and warning message.  There appears to be many major releases  of this action (currently latest version is v7.0.1) so some testing will be likely be necessary.

More info: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1700
