### ISSUE TITLE
Get UX an explanation for the Pipeline/Workspace column in artifacts

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#484]
What is a workspace here? How are pipelines being grouped, what is the difference between default/grouped column?

**Comment by rimolive** [comment]
Looks like workspaces are a multi-tenanct concept: https://www.kubeflow.org/docs/components/multi-tenancy/design/

I don't think it should be applicable to our solution as we rely on Data Science Projects.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1702
