### ISSUE TITLE
Update DSC resources to use the new image fields added to DSC

### ISSUE THREAD

**Issue by hbelmiro** [opendatahub-io/data-science-pipelines-operator#489]
Use the new image fields in `DataScienceCluster`s instead of `devFlags`.

Blocked by: https://github.com/opendatahub-io/opendatahub-operator/issues/673

**Comment by AjayJagan** [comment]
hey @hbelmiro , so regarding the addition of image fields, we created an ADR: https://github.com/opendatahub-io/architecture-decision-records/pull/23
and there is a discussion going on about this.
It would be great if you could jump in and let us know what you think 😄

**Comment by hbelmiro** [comment]
Thank you @AjayJagan. I'll keep following the discussion.
@HumairAK, you'll probably want to take a look as well.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1704
