### ISSUE TITLE
[Feature Request]: Remove VisualizationServer component

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#500]
### Feature description

VisualizationServer is a deprecated component, remove from our deployment mechanisms

**Comment by hbelmiro** [comment]
@gmfrasca doesn't it duplicate https://github.com/opendatahub-io/data-science-pipelines-operator/issues/495?

**Comment by gmfrasca** [comment]
dupe of #495
