### ISSUE TITLE
[Feature Request]: Improve V2 NetworkPolicy

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#501]
### Feature description

The NetworkPolicy for v2 argo infrastrucutre is very sparse and excessively permissive, investigate and implement a more tailored NP similar to the one used for v1-tekton

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1711
