### ISSUE TITLE
[Feature Request]: Improve/Make GetImageForComponent function dynamic

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#502]
### Feature description

GetImageForComponent takes a hard-coded set of 3 images, one per deployment permutation, which isn't very flexible.  We should instead improve it to take in more generic parameters such as 'component', 'pipelineVersion' and 'engineDriver' and use these parameters to infer and determine the correct image to return.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1712
