### ISSUE TITLE
[Feature Request]: Improve handling of db/ObjStore Avaialable Status+Error in dspipeline_controller.go

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#507]
### Feature description

The handling/passing of the status bool, error message, etc for dbAvailable and objStoreAvailable are rather messy.  Implement some way to clean them up, be it via `error`, an wrapper class, etc.

Rather than pass around strings for errs that already exist, I feel like we should update these to take in `_, dbAvailableErr`, and then have `GenerateStatus` to just take these errors in as parameters rather than a bool AND string that communicate the same thing.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1714
