### ISSUE TITLE
[Spike]: Follow up with QE on the disconnected Jenkins Pipeline.

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-operator#515]
### Feature description

Relevant issue: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/407

Follow up with @apodhrad / @StevenTobin from RHODS QE to get a timeline on the completely automated Jenkins pipeline for setting up a disconnected environment.

Acceptance criteria would be to procure links/docs from QE / folks working on the disconnected set up, on how to utilize the pipeline.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1715
