### ISSUE TITLE
[Feature Request]: Onboard e2e tests into disconnected pipeline.

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-operator#516]
### Feature description

Relevant issue: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/407

Task is to onboard DSP e2e tests on RHODS QE automated disconnected environment. 

https://github.com/opendatahub-io/data-science-pipelines-operator/issues/515 is the prerequisite to this task.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1716
