### ISSUE TITLE
Replace OpenShift Pipelines with Argo Workflows in v2 requirements

### ISSUE THREAD

**Issue by hbelmiro** [opendatahub-io/data-science-pipelines-operator#522]
Replace OpenShift Pipelines with Argo Workflows in v2 [requirements](https://github.com/opendatahub-io/data-science-pipelines-operator/tree/dspv2#pre-requisites).
Add the Argo installation link: https://argoproj.github.io/argo-workflows/quick-start/#install-argo-workflows.

**Comment by HumairAK** [comment]
related: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/532

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1718
