### ISSUE TITLE
V2 - Throw a user-friendly error when `S3CredentialSecret.SecretName` has an invalid value

### ISSUE THREAD

**Issue by hbelmiro** [opendatahub-io/data-science-pipelines-operator#523]
In v2, `S3CredentialSecret.SecretName` needs to be `mlpipeline-minio-artifact`. Right now, when a different value is set, an error saying that the `mlpipeline-minio-artifact` doesn't exist occurs. This is no user friendly. We can add validate this field and explain that this it accepts only the `mlpipeline-minio-artifact` value.

To reproduce: deploy https://github.com/opendatahub-io/data-science-pipelines-operator/tree/54ddfde1615b9a73f454e105d088c18b622fe009/config/samples/custom-configs as v2. This example has an invalid value for v2 set in https://github.com/opendatahub-io/data-science-pipelines-operator/blob/54ddfde1615b9a73f454e105d088c18b622fe009/config/samples/custom-configs/dspa.yaml#L95C8-L95C8.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1719
