### ISSUE TITLE
custom-configs sample is requiring a `mlpipeline-minio-artifact` secret

### ISSUE THREAD

**Issue by hbelmiro** [opendatahub-io/data-science-pipelines-operator#531]
Even having a secret defined, custom-configs sample requires a `mlpipeline-minio-artifact` secret when we run the pipeline.

### How to reproduce

1. Deploy the sample
2. Start a pipeline run

The pipeline will fail and a pod won't start.

```bash
iris-pipeline-37d6b-data-prep-pod                       3/5     CreateContainerConfigError
```

Error: secret "mlpipeline-minio-artifact" not found.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1720
