### ISSUE TITLE
Separate out Readme install instructions between v1/v2

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#532]
Consider moving these instructions from readme to a separate doc that's then linked within the readme and organize deployment/install instructions for v1/v2 in their respective sections. 

See docs folder here: https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main/docs

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1721
