### ISSUE TITLE
CR Images are not being applied due to config overriding 

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#67]
ATM None of the image fields in the CR work because the images provided via the config are _always_ preferred. We need to fix this such that when an image for _any_ component with a configurable image field (so not including UI and minio) is set by the CR, it is preferred over default configurations. 

Context [here](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/46#discussion_r1132895109).

**Comment by gregsheremeta** [comment]
Ref: https://issues.redhat.com/browse/RHODS-7696

**Comment by gregsheremeta** [comment]
When someone picks this up, you should add the test case from #46 to your PR.
